[package]
name = "axum-dynamodb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
axum = "0"
reqwest = "0"
tokio = { version = "1", features = ["full"] }

aws-sdk-dynamodb = "1"
aws-config = { version = "1", features = ["behavior-version-latest"] }
